---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ letsencrypt_services }}"

- name: Copying over config.json files
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ letsencrypt_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Set fact for webroot mapping
  set_fact:
    letsencrypt_webroot_map: >
      {{ { item: "/www/data/" ~ item } | combine(letsencrypt_webroot_map | default({})) }}
  with_items: "{{ letsencrypt_domains }}"

- name: Copying files for letsencrypt-acme
  vars:
    letsencrypt_acme: "{{ letsencrypt_services['letsencrypt-acme'] }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ node_config_directory }}/letsencrypt-acme/{{ item.dest }}"
    mode: "{{ item.mode | default('0660') }}"
  become: true
  with_items:
    - { src: "nginx.conf.j2", dest: "nginx.conf" }
  when:
    - inventory_hostname in groups[letsencrypt_acme.group]
    - letsencrypt_acme.enabled | bool
  notify:
    - Restart letsencrypt-acme container

- name: Copying files for letsencrypt-certbot
  vars:
    letsencrypt_certbot: "{{ letsencrypt_services['letsencrypt-certbot'] }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ node_config_directory }}/letsencrypt-certbot/{{ item.dest }}"
    mode: "{{ item.mode | default('0660') }}"
  become: true
  with_items:
    - { src: "letsencrypt.ini.j2", dest: "letsencrypt.ini" }
    - { src: "crontab.j2", dest: "crontab" }
    - { src: "certbot-renew.sh.j2", dest: "certbot-renew.sh", mode: "0770" }
    - { src: "haproxy-reload.sh.j2", dest: "haproxy-reload.sh", mode: "0770" }
  when:
    - inventory_hostname in groups[letsencrypt_certbot.group]
    - letsencrypt_certbot.enabled | bool
  notify:
    - Restart letsencrypt-certbot container

- include_tasks: check-containers.yml
  when: kolla_action != "config"
